# Generated by Django 4.0.2 on 2022-03-17 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=50)),
                ('editor_surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField(default=datetime.datetime(2022, 3, 17, 15, 33, 45, 420314))),
                ('article_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.editor')),
            ],
        ),
    ]
