# Generated by Django 4.0.2 on 2022-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_num_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='article_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
